### ISSUE TITLE
Torchscript errors

### ISSUE THREAD

**Issue by KavitShah1998** [facebookresearch/spot-sim2real#133]
Issue1 : I am getting this error about missing torchscript weights.

```
Traceback (most recent call last):
  File "/home/kavitshah/fair/spot-sim2real/spot_rl_experiments/spot_rl/utils/img_publishers.py", line 452, in <module>
    model = OWLVITModel()
  File "/home/kavitshah/fair/spot-sim2real/spot_rl_experiments/spot_rl/utils/img_publishers.py", line 363, in __init__
    self.config = config = construct_config()
  File "/home/kavitshah/fair/spot-sim2real/spot_rl_experiments/spot_rl/utils/utils.py", line 56, in construct_config
    raise KeyError(f"Neither {v} nor {new_v} exist!")
KeyError: 'Neither weights/torchscript/CUTOUT_WT_True_SD_200_ckpt.99.pvp_combined_net.torchscript nor /home/kavitshah/fair/spot-sim2real/spot_rl_experiments/weights/torchscript/CUTOUT_WT_True_SD_200_ckpt.99.pvp_combined_net.torchscript exist!'

```

Can you add a section in ISSUES.md to explain steps to resolve it?

Issue2 : Mobile Manipulation Environment fails (but Sequential Experts run fine)
```
(spot_ros) kavitshah@frerd001:~/fair/spot-sim2real/spot_rl_experiments/spot_rl/envs$ python mobile_manipulation_env.py -m
/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/albumentations/augmentations/geometric/functional.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/pretrainedmodels/datasets/utils.py:33: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  def __init__(self, size, interpolation=Image.BILINEAR):
/home/kavitshah/fair/spot-sim2real/third_party/mask_rcnn_detectron2/detectron2/detectron2/data/transforms/transform.py:46: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  def __init__(self, src_rect, output_size, interp=Image.BILINEAR, fill=0):
/home/kavitshah/fair/spot-sim2real/third_party/mask_rcnn_detectron2/detectron2/detectron2/data/transforms/augmentation_impl.py:117: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  def __init__(self, shape, interp=Image.BILINEAR):
/home/kavitshah/fair/spot-sim2real/third_party/habitat-lab/habitat/utils/visualizations/maps.py:25: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  AGENT_SPRITE = imageio.imread(
/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(
2024-02-12 15:44:59,217 - INFO - Current battery charge: 85.0%
2024-02-12 15:44:59,243 - INFO - Starting lease check-in
Loading policy...
/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/torch/serialization.py:707: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Executing automatic docking
Dock not found... trying again
Dock not found... trying again
2024-02-12 15:45:03,252 - INFO - Robot safely powered off.
2024-02-12 15:45:03,263 - INFO - Lease check-in stopped
2024-02-12 15:45:03,274 - INFO - Returned the lease.
Traceback (most recent call last):
  File "mobile_manipulation_env.py", line 423, in <module>
    main(spot, args.use_mixer, config, args.output)
  File "mobile_manipulation_env.py", line 40, in main
    policy = MixerPolicy(
  File "/home/kavitshah/fair/spot-sim2real/spot_rl_experiments/spot_rl/real_policy.py", line 298, in __init__
    super().__init__(
  File "/home/kavitshah/fair/spot-sim2real/spot_rl_experiments/spot_rl/real_policy.py", line 76, in __init__
    self.policy = policy_class.from_config(
  File "/home/kavitshah/fair/spot-sim2real/third_party/habitat-lab/habitat_baselines/rl/ppo/moe.py", line 172, in from_config
    return cls(
  File "/home/kavitshah/fair/spot-sim2real/third_party/habitat-lab/habitat_baselines/rl/ppo/moe.py", line 442, in __init__
    super().__init__(
  File "/home/kavitshah/fair/spot-sim2real/third_party/habitat-lab/habitat_baselines/rl/ppo/moe.py", line 114, in __init__
    nav_ckpt, self.expert_nav_policy = get_ckpt_policy(nav_ckpt_path)
  File "/home/kavitshah/fair/spot-sim2real/third_party/habitat-lab/habitat_baselines/rl/ppo/moe.py", line 109, in get_ckpt_policy
    ckpt["config"].RL.POLICY["init"] = False
  File "/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/torch/jit/_script.py", line 838, in __getitem__
    return self.forward_magic_method("__getitem__", idx)
  File "/home/kavitshah/miniforge3/envs/spot_ros/lib/python3.8/site-packages/torch/jit/_script.py", line 831, in forward_magic_method
    raise NotImplementedError()
NotImplementedError
2024-02-12 15:45:03,276 - INFO - signal_shutdown [atexit]

```

**Comment by tusharsangam** [comment]
There's no elegant fix for this, thus I have made two sections of weights i.e. one for pytorch & other for torchscript in config.yaml, when using MixerNetwork traditional weights section should be loaded & other skills can be either loaded from torchscript or pytorch depending on WEIGHTS_TYPE variable in config.yaml.
Hope that unblocks you @KavitShah1998

**Comment by KavitShah1998** [comment]
LGTM
